#!/bin/bash
#
# Required files: (NB Tab files depend on the one above)
# Having Astrometry installed and functioning
# ImageCalibration.sh
#	GrabFrame2Fits.m
#		RawDMCreader.m
#			GetRawInd.m
#	GetMagAndPixelsForBrightStars.m
#		StarPixelCount.m	
#
# We wanna cycle through the night and get all the bright stars to fit our image!
# First of all give an image to Astrometry to recongize it and have it printe the .wcs file
# Insert folder where the image is stored

declare -i MeteoroidNumber
declare -i dummycounter
#declare -a MeteoroidsExcelLocation=(4 5 7 9 11 18 23 26 28) #30th of March
declare -a MeteoroidsExcelLocation=(1 3 24 32 46 50 52 60 65 66 72) #31st of March
declare -i START


NFRAMES=150;  # of frames you want to stack when doing analysis. Ideally frames=FrameRate*PixelArcseconds/2*1/(StarsSecondsDrift)
# star second drift is the angular drift of the star in the night sky ~ 360deg/86400 sec
day="Day31032014"; # the night you are analyzing
#NightToBeAnalyzed="/mnt/NAS/Ultra/2014-03-30/2014-03-30T10-46-CamSer7196.DMCdata"
NightToBeAnalyzed="/media/limo/My Passport/2014-03-31/2014-03-31T06-12-CamSer7196.DMCdata"; #where the file being read is located
Folder="/home/limo/PHD/PokerFlat2014/AzDecImages"; # where are you storing all the files generated by the scripts 
TychoCataloguePath="/home/limo/PHD/astrometry.net-0.73/catalogs/tycho2.kd" # Where you have placed you Tycho Catalogue!!!
MeteorLuminosityFile="/home/limo/PHD/PokerFlat2014/MatlabCode/Data/20140331Meteoroids.mat" #contains luminosity and position of the meteor
export PYTHONPATH=/usr/local/astrometry/lib/python

#MeteoroidNumber=1
dummycounter=0

while IFS=" " read a b
do	
	MeteoroidNumber=${MeteoroidsExcelLocation[$dummycounter]}
	inizio=$a
	fine=$b
	echo inizio
	echo fine	
	echo $dummycounter
	echo ${MeteoroidsExcelLocation[0]}
	echo $MeteoroidNumber

	START=$a-80;   #where you start your frame, the stacking will be centered around this frame, i.e. BegFrame-round(NFRAMES/2):BegFrame+rounds(NFRAMES/2)
		       #for our camera it's about 69 arcseconds/pixel --> ~ 100 
	echo $START

	BegFrame=$START;   # The frame aboud which you are doing the stacking
	echo "Reading Frame" $START
	BrightStarsAstroOutputFile="/home/limo/PHD/PokerFlat2014/AzDecImages/BrightStarsOutput"$BegFrame""$day".txt"; #where you are outputting the BrightStars detected by astrometry, you also feed it to matlab to find the location of the stars with their magnitude to be used for the calibration

	# Insert Name of the Image
	imageName="/Frame"$BegFrame$day".fits";
	imageWCS="/Frame"$BegFrame$day".wcs"
	dataName="/Frame"$BegFrame$day".mat";
	TableImageStars="/Frame"$BegFrame$day".wcs"; #wcs file with the stars found in the image
	SavedStars="/$BegFrame$Stars"$day".mat"; # this is where you save the stars for the days, it is used in the GetMagAndPixelForBrightStars where they are extracted in 						order to be used for the calibration, since it's been done Ntime we locally store them somewhere

	# Latitude in degrees [-90:90] of where you took the pic
	lat=65.116693 #PokerFlat
	# Longitutude in degrees [-180:180] of where you took the pic
	long=-147.48802209999997 #Poker Flat
	# tUTC in string format "YYYY/MM/DD hh:mm:ss"
	# Number of x pixels
	Xpixmin=1
	Xpixmax=512
	# Number of y pixels
	Ypixmin=1
	Ypixmax=512
	# Limiting magnitude of the Stars You hope to extract from the image
	LimitMag=10

	# Grabe the frame of interest and its time
	echo "Entering Matlab To Grab Frame"
	matlab -nodesktop -nosplash -nodisplay -r "GrabFrame2fits($BegFrame,$NFRAMES,'$NightToBeAnalyzed','$day','$Folder','$imageName','$dataName'); quit;"
	tUTCfilename=$Folder"/Frame"$BegFrame$day"Time.txt"
	tUTC=`cat $Folder"/Frame"$BegFrame$day"Time".txt`
	echo "After Matlab"
	echo "Using astrometry to find field"

	# Call Astrometry solve fields to match image with night sky, N.B. there can be several interesting parameters that can be added, especially limitation on 		where to look. N.B. Astrometry solves for Right Ascension and Declination
	# N.B. the images are stored in the same folder as where the original image
	solve-field $Folder$imageName --overwrite --tag-all

	#
	# Call astrometry to give you the frame and pixel location of any bright stars in your frame
	#
	echo "Finding the pixel location of any bright star in my field"
	echo "Frame*"$BegFrame"*" > $BrightStarsAstroOutputFile

	# Using tycho2 (best out of them all)
	echo "Tagging stars with Tych2 catalogue"
	plotann.py --tycho2cat $TychoCataloguePath $Folder$TableImageStars>>$BrightStarsAstroOutputFile --rd=RD
	echo "Grabbing Mag and Pixels For Bright Stars"
	matlab -nodesktop -nosplash -nodisplay -r "GetMagAndPixelsForBrightStars('$BrightStarsAstroOutputFile',$Xpixmax,$Ypixmax,$LimitMag,'$Folder$dataName','$Folder$SavedStars','$tUTCfilename',$lat,$long); quit;"
	#
	# GRAB AZ AND ELEVATION MATRICES FOR EACH MEAN FRAME, UNCOMMENT FROM HERE TO THE END OF THE FILE IF YOU WANNA DO THAT AS WELL
	#
	#Hoping/Assuming a succesfull match has been found by solve-fields let's call (don't remember what) which goes on converting each pixel to a txt file 		containing right ascension and declination. Unccomment the following lines, if beside the star brightness you want to also have the Azimuth and Elevation 		matrix

#	echo 'Finding all pixel RA and DEC txt file' # AllPixels.fits is needed for this, it's a fits table that contains the x-pixel and y-pixel values needed to convert image into RA-DEC values. NB, the values are such that the first 512 rows are: x=1,y=1:512; second 512 rows: x=2,y=1:512
#	echo $Folder$imageWCS 
	wcs-xy2rd -w $Folder$imageWCS -i /home/limo/PHD/astrometry.net-0.73/AllPixels.fits -o /home/limo/PHD/PokerFlat2014/AzDecImages/RaDeclValue$BegFrame.fits
	# Let's convert into txt file
	tablist /home/limo/PHD/PokerFlat2014/AzDecImages/RaDeclValue$BegFrame.fits > /home/limo/PHD/PokerFlat2014/AzDecImages/RaDeclValue$BegFrame.txt
	# Congratulation in making it so far now we call a matlab script to convert from RA and DEC to azimuth and elevation
	RaDeclFile=/home/limo/PHD/PokerFlat2014/AzDecImages/RaDeclValue$BegFrame.txt
#	echo 'Converting to Az and El'
	matlab -nodesktop -nosplash -nodisplay -r "NewWay2GrabRaDecConvert2AzElforImageCalibration('$RaDeclFile','$Folder','$imageName','$Xpixmax','$Ypixmax','$lat','$long','$tUTCfilename'); quit;"
	#
	# END OF THE GRAB AZ AND ELEVATION PART
	#
	echo 'Computing Meteor Magnitude'
	RaDecAzElFile="$Folder/RaDecAzElFrame$BegFrame$day.mat"
	matlab -nodesktop -nosplash -nodisplay -r "MeteorMagnitudeEstimationNotDetectedByAutoAlgo('$Folder','$day','$Folder$SavedStars','$RaDecAzElFile',$inizio,$fine);quit"

#rm -r $Folder"/Frame"$BegFrame$day*		
#rm -r $Folder"/BrightStars"*	
#rm -r $Folder"/AzFrame"*
#rm -r $Folder"/ElFrame"*
#rm -r $Folder"/DeclFrame"*
#rm -r $Folder"/RaFrame"*
#MeteoroidNumber=$MeteoroidNumber+1;
dummycounter=dummycounter+1;
echo $MeteoroidNumber
done < /home/limo/PHD/astrometry.net-0.73/astrometry/SelectedMeteoroids31032014.txt
